title: CustomerController
modelClass: NielsVanDenDries\Assetmanagement\Models\CustomerModel
list: $/nielsvandendries/assetmanagement/models/customermodel/columns.yaml
recordUrl: 'nielsvandendries/assetmanagement/customercontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
